name: Test TinyIoT Thing Directory

on: 
  push:
    paths:
    - 'directory/**'
  pull_request:
    paths:
    - 'directory/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run server
      run: docker run --name=tdd -p 8081:8081 -d ghcr.io/tinyiot/thing-directory
    
    - name: Test
      if: success()
      run: go test --server=http://localhost:8081
      working-directory: directory

    - name: Export report as artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: report-tinyiot-thing-directory
        path: directory/report/tdd-auto.csv
    
    - name: Print server logs
      if: always()
      run: docker logs tdd
